/**
 * Parity test: JS foundationSolids output must match the Python golden.
 *
 * Run from repo root: node tests/foundation_parity.mjs
 *
 * The golden (tests/fixtures/foundation_golden.json) was generated by
 * tests/gen_foundation_golden.py from foundation_lib.py. This test runs the JS
 * region flood-fill (region.js computeRegion) + foundation derivation
 * (foundation_geom.js foundationSolids) over the SAME fixtures and asserts the
 * ordered piece list (labels, kinds, dims, centers) matches within tolerance —
 * exercising both a rectangular AND an L-shaped silhouette so the flood-fill
 * parity is actually tested.
 *
 * Parity contract: foundation_geom.js <-> foundation_lib.py must stay in sync.
 */
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

import { computeRegion } from '../web/js/region.js';
import { foundationSolids } from '../web/js/foundation_geom.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixDir = path.join(__dirname, 'fixtures');

const golden = JSON.parse(readFileSync(path.join(fixDir, 'foundation_golden.json'), 'utf8'));
const TOL = 1e-6; // mm — both sides are float64 doing the same arithmetic

// Adapt a JSON entity (module/direction/width_mm/depth_mm) to the in-memory
// shape region.js / foundation_geom.js consume (mod object + dir).
function adapt(e) {
  return {
    id: e.id, kind: e.kind, dir: e.direction, x_mm: e.x_mm, y_mm: e.y_mm,
    mod: { id: e.module, width_mm: e.width_mm, depth_mm: e.depth_mm },
  };
}

let passed = 0, failed = 0;

function near(a, b, label, errs) {
  if (Math.abs(a - b) > TOL) { errs.push(`${label}: got ${a}, expected ${b}`); return false; }
  return true;
}

// --- structural expectations (the anti-regression contract) ----------------
// EXACT piece counts: monolithic slab (NOT per-row strips), one beam + one
// skirt per perimeter RUN (NOT per wall module). slab is a range on the L
// because cell quantization can split the silhouette into 2 or 3 maximal rects.
const EXPECT = {
  foundation_rect: { slab: [1, 1], beam: 4, skirt: 4 },
  foundation_L:    { slab: [2, 3], beam: 6, skirt: 6 },
};

function aabbOf(pc) {
  const { dx_mm: dx, dy_mm: dy } = pc.dims;
  const { x_mm: cx, y_mm: cy } = pc.center;
  return { x0: cx - dx / 2, x1: cx + dx / 2, y0: cy - dy / 2, y1: cy + dy / 2, cx, cy };
}
const letterOf = pc => pc.label.split('_')[1];

// Continuity check: every building CORNER (derived from the BEAMS — one per run,
// on the wall centerline, unaffected by any skirt bug) must be covered by a
// skirt. If the corner-extension is missing, the corner-square sample falls in
// the diagonal gap and is covered by NO skirt → fail. Returns [] or [errors].
function skirtContinuityErrors(pieces) {
  const PAD = 1e-6;
  const T = 304.8; // ~beam width — corner = a run end meeting a perpendicular run line
  const beams = pieces.filter(p => p.kind === 'beam').map(p => {
    const a = aabbOf(p);
    const horiz = p.dims.dx_mm >= p.dims.dy_mm;
    return { letter: letterOf(p), horiz, a };
  });
  const skirts = {};
  for (const p of pieces.filter(p => p.kind === 'skirt')) skirts[letterOf(p)] = aabbOf(p);
  const skirtAABBs = Object.values(skirts);
  const inside = (x, y) => skirtAABBs.some(s =>
    x >= s.x0 - PAD && x <= s.x1 + PAD && y >= s.y0 - PAD && y <= s.y1 + PAD);

  const errs = [];
  const hs = beams.filter(b => b.horiz), vs = beams.filter(b => !b.horiz);
  for (const h of hs) for (const v of vs) {
    const hy = h.a.cy;                 // horiz run centerline y
    const vx = v.a.cx;                 // vert run centerline x
    const nearXend = Math.min(Math.abs(vx - h.a.x0), Math.abs(vx - h.a.x1)) <= T;
    const nearYend = Math.min(Math.abs(hy - v.a.y0), Math.abs(hy - v.a.y1)) <= T;
    if (!(nearXend && nearYend)) continue; // not a corner of the building
    // sample the corner square at the crossing of the two skirts' thin bands
    const sx = skirts[v.letter].cx, sy = skirts[h.letter].cy;
    if (!inside(sx, sy)) errs.push(`corner ${h.letter}×${v.letter} @ (${sx.toFixed(1)},${sy.toFixed(1)}) not covered by any skirt`);
  }
  return errs;
}

function structuralErrors(name, pieces) {
  const exp = EXPECT[name];
  if (!exp) return [];
  const errs = [];
  const count = k => pieces.filter(p => p.kind === k).length;
  const slab = count('slab'), beam = count('beam'), skirt = count('skirt');
  if (slab < exp.slab[0] || slab > exp.slab[1]) errs.push(`slab count ${slab} not in [${exp.slab}] (monolithic, not per-row strips)`);
  if (beam !== exp.beam) errs.push(`beam count ${beam}, expected ${exp.beam} (one per run)`);
  if (skirt !== exp.skirt) errs.push(`skirt count ${skirt}, expected ${exp.skirt} (one per run)`);
  errs.push(...skirtContinuityErrors(pieces));
  return errs;
}

for (const [name, want] of Object.entries(golden)) {
  const data = JSON.parse(readFileSync(path.join(fixDir, `${name}.json`), 'utf8'));
  const ents = (data.entities || data.modules || []).map(adapt);
  const l1Walls = ents.filter(e => e.kind === 'wall' && (e.level || 'L1') === 'L1');
  const region = computeRegion(ents);
  const silhouette = {
    rects: region.rects,
    walls: l1Walls.map(w => ({ id: w.id, x_mm: w.x_mm, y_mm: w.y_mm, mod: w.mod, dir: w.dir })),
    containsPoint: region.containsPoint,
    cell_mm: region.cells ? region.cells.cell_mm : undefined,
  };
  const got = foundationSolids(want.params, silhouette);

  const errs = [];
  // structural contract (exact run counts + gapless skirt loop) on the JS output
  errs.push(...structuralErrors(name, got));

  // OUTSIDE assertion: every skirt must sit on the exterior. A skirt placed on
  // the wrong face (probe bug) has its center inside the building. Probe ±cell in
  // the skirt's thin dimension: a correctly placed skirt has one probe clearly in
  // FLOOD (exterior), a flipped skirt has both probes inside (WALL or interior).
  // We probe ±cell rather than the center itself because the region grid can
  // over-mark exterior cells within 1 cell of the wall outer face as WALL.
  const cell = silhouette.cell_mm || 76.2;
  for (const p of got.filter(p => p.kind === 'skirt')) {
    const { x_mm: cx, y_mm: cy } = p.center;
    const horiz = p.dims.dx_mm > p.dims.dy_mm;
    const outside = horiz
      ? (!silhouette.containsPoint(cx, cy - cell) || !silhouette.containsPoint(cx, cy + cell))
      : (!silhouette.containsPoint(cx - cell, cy) || !silhouette.containsPoint(cx + cell, cy));
    if (!outside) {
      errs.push(`skirt ${p.label} center (${cx.toFixed(1)},${cy.toFixed(1)}) — both ±cell probes inside silhouette, skirt likely on wrong face`);
    }
  }

  if (got.length !== want.pieces.length) {
    errs.push(`piece count: got ${got.length}, expected ${want.pieces.length}`);
  }
  const n = Math.min(got.length, want.pieces.length);
  for (let i = 0; i < n; i++) {
    const g = got[i], w = want.pieces[i];
    if (g.label !== w.label) errs.push(`[${i}] label: got ${g.label}, expected ${w.label}`);
    if (g.kind !== w.kind) errs.push(`[${i}] kind: got ${g.kind}, expected ${w.kind}`);
    for (const k of ['dx_mm', 'dy_mm', 'dz_mm']) near(g.dims[k], w.dims[k], `[${i}] dims.${k}`, errs);
    for (const k of ['x_mm', 'y_mm', 'z_mm']) near(g.center[k], w.center[k], `[${i}] center.${k}`, errs);
  }

  if (errs.length) {
    console.error(`FAIL ${name} (${want.pieces.length} pieces)`);
    for (const e of errs.slice(0, 12)) console.error('  ' + e);
    failed++;
  } else {
    console.log(`PASS ${name} (${want.pieces.length} pieces)`);
    passed++;
  }
}

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
