/**
 * Parity test: JS foundationSolids output must match the Python golden.
 *
 * Run from repo root: node tests/foundation_parity.mjs
 *
 * The golden (tests/fixtures/foundation_golden.json) was generated by
 * tests/gen_foundation_golden.py from foundation_lib.py. This test runs the JS
 * region flood-fill (region.js computeRegion) + foundation derivation
 * (foundation_geom.js foundationSolids) over the SAME fixtures and asserts the
 * ordered piece list (labels, kinds, dims, centers) matches within tolerance —
 * exercising both a rectangular AND an L-shaped silhouette.
 *
 * Structural contract (beyond byte parity): BOTH the grade-beam RING and the
 * frost-skirt LOOP are sets of NON-OVERLAPPING boxes forming a single connected
 * loop with an open interior. The skirt sits 1" outside the beam outer face and
 * 1" below the beam top.
 *
 * Parity contract: foundation_geom.js <-> foundation_lib.py must stay in sync.
 */
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

import { computeRegion } from '../web/js/region.js';
import { foundationSolids } from '../web/js/foundation_geom.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixDir = path.join(__dirname, 'fixtures');

const golden = JSON.parse(readFileSync(path.join(fixDir, 'foundation_golden.json'), 'utf8'));
const TOL = 1e-6; // mm — both sides are float64 doing the same arithmetic

const INSET_MM = 25.4;   // skirt 1" outside beam outer face
const BEAM_TOP_Z = -5;   // beam top 5 mm below slab datum

function adapt(e) {
  return {
    id: e.id, kind: e.kind, dir: e.direction, x_mm: e.x_mm, y_mm: e.y_mm,
    mod: { id: e.module, width_mm: e.width_mm, depth_mm: e.depth_mm },
  };
}

let passed = 0, failed = 0;

function near(a, b, label, errs) {
  if (Math.abs(a - b) > TOL) { errs.push(`${label}: got ${a}, expected ${b}`); return false; }
  return true;
}

// slab exact-ish; beam + skirt are loops of N boxes (footprint-dependent), so
// assert a sane range plus structural loop checks rather than an exact count.
const EXPECT = {
  foundation_rect: { slab: [1, 1], beam: [4, 8], skirt: [4, 8] },
  foundation_L:    { slab: [2, 3], beam: [6, 12], skirt: [6, 12] },
};

function aabbOf(pc) {
  const { dx_mm: dx, dy_mm: dy } = pc.dims;
  const { x_mm: cx, y_mm: cy } = pc.center;
  return { x0: cx - dx / 2, x1: cx + dx / 2, y0: cy - dy / 2, y1: cy + dy / 2, cx, cy };
}

// NO OVERLAP: no two boxes of `kind` share positive plan area.
function overlapErrors(pieces, kind) {
  const bs = pieces.filter(p => p.kind === kind).map(aabbOf);
  const PAD = 1e-6, errs = [];
  for (let i = 0; i < bs.length; i++) for (let j = i + 1; j < bs.length; j++) {
    const a = bs[i], b = bs[j];
    const ox = Math.min(a.x1, b.x1) - Math.max(a.x0, b.x0);
    const oy = Math.min(a.y1, b.y1) - Math.max(a.y0, b.y0);
    if (ox > PAD && oy > PAD) errs.push(`${kind} boxes [${i}]&[${j}] overlap by ${ox.toFixed(1)}×${oy.toFixed(1)}`);
  }
  return errs;
}

// SINGLE LOOP: boxes of `kind` form one connected component (touching counts).
function loopErrors(pieces, kind) {
  const bs = pieces.filter(p => p.kind === kind).map(aabbOf);
  if (bs.length < 2) return [];
  const E = 0.01;
  const touch = (a, b) =>
    (Math.min(a.x1, b.x1) - Math.max(a.x0, b.x0)) > -E &&
    (Math.min(a.y1, b.y1) - Math.max(a.y0, b.y0)) > -E;
  const par = bs.map((_, i) => i);
  const find = x => { while (par[x] !== x) { par[x] = par[par[x]]; x = par[x]; } return x; };
  for (let i = 0; i < bs.length; i++) for (let j = i + 1; j < bs.length; j++)
    if (touch(bs[i], bs[j])) par[find(i)] = find(j);
  const comps = new Set(bs.map((_, i) => find(i)));
  return comps.size === 1 ? [] : [`${kind} is ${comps.size} components, not one connected loop`];
}

// OPEN INTERIOR: the beam is a RING — a slab interior sample must NOT be covered
// by any beam box (proves it's a ring, not a filled blob).
function beamRingHoleErrors(pieces) {
  const beams = pieces.filter(p => p.kind === 'beam').map(aabbOf);
  const slabs = pieces.filter(p => p.kind === 'slab').map(aabbOf);
  const errs = [];
  for (const s of slabs) {
    if (beams.some(b => s.cx > b.x0 && s.cx < b.x1 && s.cy > b.y0 && s.cy < b.y1))
      errs.push(`slab center (${s.cx.toFixed(1)},${s.cy.toFixed(1)}) is inside a beam — ring not open`);
  }
  return errs;
}

// 1" GAP: each skirt box sits exactly INSET_MM from its nearest facing beam.
function skirtGapErrors(pieces) {
  const beams = pieces.filter(p => p.kind === 'beam').map(aabbOf);
  const TOLmm = 0.5, errs = [];
  for (const s of pieces.filter(p => p.kind === 'skirt')) {
    const sa = aabbOf(s);
    let best = Infinity;
    for (const b of beams) {
      const sepx = Math.max(sa.x0 - b.x1, b.x0 - sa.x1);
      const sepy = Math.max(sa.y0 - b.y1, b.y0 - sa.y1);
      if (sepx <= 0 && sepy > 0) best = Math.min(best, sepy);
      else if (sepy <= 0 && sepx > 0) best = Math.min(best, sepx);
    }
    if (Math.abs(best - INSET_MM) > TOLmm) errs.push(`${s.label} nearest-beam gap ${best.toFixed(2)} != 1" (${INSET_MM})`);
  }
  return errs;
}

// Z: skirt height = beamD - 1", top 1" below beam top.
function skirtZErrors(pieces, params) {
  const beamD = params.beam_d_mm, TOLmm = 0.1, errs = [];
  const expDZ = beamD - INSET_MM;
  const expCZ = (BEAM_TOP_Z - INSET_MM) - expDZ / 2;
  for (const s of pieces.filter(p => p.kind === 'skirt')) {
    if (Math.abs(s.dims.dz_mm - expDZ) > TOLmm) errs.push(`${s.label} dz ${s.dims.dz_mm.toFixed(2)} != ${expDZ.toFixed(2)}`);
    if (Math.abs(s.center.z_mm - expCZ) > TOLmm) errs.push(`${s.label} cz ${s.center.z_mm.toFixed(2)} != ${expCZ.toFixed(2)}`);
  }
  return errs;
}

function structuralErrors(name, pieces) {
  const exp = EXPECT[name];
  if (!exp) return [];
  const errs = [];
  const count = k => pieces.filter(p => p.kind === k).length;
  const inRange = (n, [lo, hi]) => n >= lo && n <= hi;
  const slab = count('slab'), beam = count('beam'), skirt = count('skirt');
  if (slab < exp.slab[0] || slab > exp.slab[1]) errs.push(`slab count ${slab} not in [${exp.slab}]`);
  if (!inRange(beam, exp.beam)) errs.push(`beam count ${beam} not in [${exp.beam}]`);
  if (!inRange(skirt, exp.skirt)) errs.push(`skirt count ${skirt} not in [${exp.skirt}]`);
  errs.push(...overlapErrors(pieces, 'beam'));
  errs.push(...loopErrors(pieces, 'beam'));
  errs.push(...beamRingHoleErrors(pieces));
  errs.push(...overlapErrors(pieces, 'skirt'));
  errs.push(...loopErrors(pieces, 'skirt'));
  return errs;
}

for (const [name, want] of Object.entries(golden)) {
  const data = JSON.parse(readFileSync(path.join(fixDir, `${name}.json`), 'utf8'));
  const ents = (data.entities || data.modules || []).map(adapt);
  const l1Walls = ents.filter(e => e.kind === 'wall' && (e.level || 'L1') === 'L1');
  const region = computeRegion(ents);
  const silhouette = {
    rects: region.rects,
    walls: l1Walls.map(w => ({ id: w.id, x_mm: w.x_mm, y_mm: w.y_mm, mod: w.mod, dir: w.dir })),
    containsPoint: region.containsPoint,
    cell_mm: region.cells ? region.cells.cell_mm : undefined,
  };
  const got = foundationSolids(want.params, silhouette);

  const errs = [];
  errs.push(...structuralErrors(name, got));
  errs.push(...skirtGapErrors(got));
  errs.push(...skirtZErrors(got, want.params));

  // OUTSIDE assertion: every skirt box center must be exterior.
  for (const p of got.filter(p => p.kind === 'skirt')) {
    if (silhouette.containsPoint(p.center.x_mm, p.center.y_mm))
      errs.push(`skirt ${p.label} center is inside the silhouette (should be exterior)`);
  }

  if (got.length !== want.pieces.length) errs.push(`piece count: got ${got.length}, expected ${want.pieces.length}`);
  const n = Math.min(got.length, want.pieces.length);
  for (let i = 0; i < n; i++) {
    const g = got[i], w = want.pieces[i];
    if (g.label !== w.label) errs.push(`[${i}] label: got ${g.label}, expected ${w.label}`);
    if (g.kind !== w.kind) errs.push(`[${i}] kind: got ${g.kind}, expected ${w.kind}`);
    for (const k of ['dx_mm', 'dy_mm', 'dz_mm']) near(g.dims[k], w.dims[k], `[${i}] dims.${k}`, errs);
    for (const k of ['x_mm', 'y_mm', 'z_mm']) near(g.center[k], w.center[k], `[${i}] center.${k}`, errs);
  }

  if (errs.length) {
    console.error(`FAIL ${name} (${want.pieces.length} pieces)`);
    for (const e of errs.slice(0, 12)) console.error('  ' + e);
    failed++;
  } else {
    console.log(`PASS ${name} (${want.pieces.length} pieces)`);
    passed++;
  }
}

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
