/**
 * Parity test: JS foundationSolids output must match the Python golden.
 *
 * Run from repo root: node tests/foundation_parity.mjs
 *
 * The golden (tests/fixtures/foundation_golden.json) was generated by
 * tests/gen_foundation_golden.py from foundation_lib.py. This test runs the JS
 * region flood-fill (region.js computeRegion) + foundation derivation
 * (foundation_geom.js foundationSolids) over the SAME fixtures and asserts the
 * ordered piece list (labels, kinds, dims, centers) matches within tolerance —
 * exercising both a rectangular AND an L-shaped silhouette so the flood-fill
 * parity is actually tested.
 *
 * Parity contract: foundation_geom.js <-> foundation_lib.py must stay in sync.
 */
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

import { computeRegion } from '../web/js/region.js';
import { foundationSolids } from '../web/js/foundation_geom.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixDir = path.join(__dirname, 'fixtures');

const golden = JSON.parse(readFileSync(path.join(fixDir, 'foundation_golden.json'), 'utf8'));
const TOL = 1e-6; // mm — both sides are float64 doing the same arithmetic

// Adapt a JSON entity (module/direction/width_mm/depth_mm) to the in-memory
// shape region.js / foundation_geom.js consume (mod object + dir).
function adapt(e) {
  return {
    id: e.id, kind: e.kind, dir: e.direction, x_mm: e.x_mm, y_mm: e.y_mm,
    mod: { id: e.module, width_mm: e.width_mm, depth_mm: e.depth_mm },
  };
}

let passed = 0, failed = 0;

function near(a, b, label, errs) {
  if (Math.abs(a - b) > TOL) { errs.push(`${label}: got ${a}, expected ${b}`); return false; }
  return true;
}

for (const [name, want] of Object.entries(golden)) {
  const data = JSON.parse(readFileSync(path.join(fixDir, `${name}.json`), 'utf8'));
  const ents = (data.entities || data.modules || []).map(adapt);
  const l1Walls = ents.filter(e => e.kind === 'wall' && (e.level || 'L1') === 'L1');
  const region = computeRegion(ents);
  const silhouette = {
    rects: region.rects,
    walls: l1Walls.map(w => ({ id: w.id, x_mm: w.x_mm, y_mm: w.y_mm, mod: w.mod, dir: w.dir })),
    containsPoint: region.containsPoint,
    cell_mm: region.cells ? region.cells.cell_mm : undefined,
  };
  const got = foundationSolids(want.params, silhouette);

  const errs = [];
  if (got.length !== want.pieces.length) {
    errs.push(`piece count: got ${got.length}, expected ${want.pieces.length}`);
  }
  const n = Math.min(got.length, want.pieces.length);
  for (let i = 0; i < n; i++) {
    const g = got[i], w = want.pieces[i];
    if (g.label !== w.label) errs.push(`[${i}] label: got ${g.label}, expected ${w.label}`);
    if (g.kind !== w.kind) errs.push(`[${i}] kind: got ${g.kind}, expected ${w.kind}`);
    for (const k of ['dx_mm', 'dy_mm', 'dz_mm']) near(g.dims[k], w.dims[k], `[${i}] dims.${k}`, errs);
    for (const k of ['x_mm', 'y_mm', 'z_mm']) near(g.center[k], w.center[k], `[${i}] center.${k}`, errs);
  }

  if (errs.length) {
    console.error(`FAIL ${name} (${want.pieces.length} pieces)`);
    for (const e of errs.slice(0, 12)) console.error('  ' + e);
    failed++;
  } else {
    console.log(`PASS ${name} (${want.pieces.length} pieces)`);
    passed++;
  }
}

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
