/**
 * Parity test: JS createBlocking output must match the FreeCAD-generated golden.
 *
 * Run from repo root: node tests/parity.mjs
 *
 * The golden (tests/fixtures/golden.json) was generated by tests/gen_golden.py
 * running under FreeCAD. It encodes the bounding box of each blocking piece as
 * produced by compile_from_json.create_blocking. This test asserts that the JS
 * createBlocking in web/js/fcstd.js produces identical geometry.
 *
 * Parity contract: both implementations must stay in sync — see tests/parity.mjs
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

import { _test } from '../web/js/fcstd.js';

const golden = JSON.parse(readFileSync(path.join(__dirname, 'fixtures', 'golden.json'), 'utf8'));

const FIXTURES = ['layout_c1', 'layout_c2', 'layout_t', 'layout_multi'];
const TOL = 1e-3; // mm

let passed = 0, failed = 0;

function near(a, b, tol, label) {
  if (Math.abs(a - b) > tol) {
    console.error(`  FAIL ${label}: got ${a}, expected ${b} (diff ${Math.abs(a-b).toExponential(3)})`);
    return false;
  }
  return true;
}

for (const fname of FIXTURES) {
  const fixture = JSON.parse(readFileSync(
    path.join(__dirname, 'fixtures', `${fname}.json`), 'utf8'));

  const entities = fixture.entities || fixture.modules || [];
  const minx = Math.min(...entities.map(e => e.x_mm));
  const miny = Math.min(...entities.map(e => e.y_mm));

  const byId = {};
  for (const e of entities) {
    byId[e.id] = { mod: { id: e.module }, dir: e.direction, x_mm: e.x_mm, y_mm: e.y_mm };
  }

  let pieceIdx = 0;
  let fixtureFailed = false;

  for (const e of entities) {
    for (const conn of (e.connections || [])) {
      const pieces = _test.createBlocking(conn, byId, minx, miny);
      for (const [dx, dy, dz, tx, ty, tz] of pieces) {
        const key = `${fname}/${pieceIdx}`;
        const g = golden[key];
        if (!g) {
          console.error(`  FAIL ${key}: not in golden`);
          fixtureFailed = true;
          pieceIdx++;
          continue;
        }
        const ok = near(dx, g.dx, TOL, `${key}.dx`)
                && near(dy, g.dy, TOL, `${key}.dy`)
                && near(dz, g.dz, TOL, `${key}.dz`)
                && near(tx, g.tx, TOL, `${key}.tx`)
                && near(ty, g.ty, TOL, `${key}.ty`)
                && near(tz, g.tz, TOL, `${key}.tz`);
        if (!ok) fixtureFailed = true;
        pieceIdx++;
      }
    }
  }

  // Verify expected piece count matches golden
  const goldenCount = Object.keys(golden).filter(k => k.startsWith(fname + '/')).length;
  if (pieceIdx !== goldenCount) {
    console.error(`  FAIL ${fname}: got ${pieceIdx} pieces, golden has ${goldenCount}`);
    fixtureFailed = true;
  }

  if (fixtureFailed) {
    console.error(`FAIL ${fname}`);
    failed++;
  } else {
    console.log(`PASS ${fname} (${pieceIdx} pieces)`);
    passed++;
  }
}

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
