// =====================================================
// FOUNDATION — the autogen popup for the Foundation trade.
// Mirrors the Project Options modal pattern (options.js): a small set of
// climate/recon-prefilled fields, a green GO that is valid-on-open, and the
// "pick once, autogenerate downstream" proof-of-concept (skirt depth is the one
// climate-driven field, read from doc.project.climate.frost_mm).
//
// GO writes ONE derived foundation entity (params only — geometry is recomputed
// from the L1 silhouette at render/BOM time) and fires 'iconic:foundation', which
// trades.js handles to enter the foundation REVIEW view.
// =====================================================
import { doc, ui } from './state.js';
import { markModelChanged } from './app.js';

// Autogen defaults (mm). Slab 4", grade beam 12"×18". Skirt depth is overridden
// per-project from the climate frost depth on open.
const DEFAULTS = { slab: 101.6, beamW: 304.8, beamD: 457.2 };
// Fixed, not exposed (spec): skirt thickness 2".
const SKIRT_THICKNESS_MM = 50.8;

const form  = { skirt: 750, slab: DEFAULTS.slab, beamW: DEFAULTS.beamW, beamD: DEFAULTS.beamD };
let   _auto = { ...form }; // the autogenerated values, to detect manual edits

const round1 = v => Math.round(v * 10) / 10;

function validate() {
  // Every field is a positive number → GO green on open (defaults are valid).
  const ok = [form.skirt, form.slab, form.beamW, form.beamD]
    .every(v => Number.isFinite(v) && v > 0);
  const go = document.getElementById('fnd-go');
  if (go) go.disabled = !ok;
  return ok;
}

let _warnTimer = null;
function flashEditWarn() {
  const w = document.getElementById('fnd-warn');
  if (!w) return;
  w.classList.add('show');
  clearTimeout(_warnTimer);
  _warnTimer = setTimeout(() => w.classList.remove('show'), 5000);
}

// Any field moved off its autogenerated value flashes the engineering warning.
function checkEdited() {
  if (form.skirt !== _auto.skirt || form.slab !== _auto.slab ||
      form.beamW !== _auto.beamW || form.beamD !== _auto.beamD) {
    flashEditWarn();
  }
}

export function openFoundationModal() {
  // Skirt depth = the project's climate frost depth (the autogenerate demo).
  const frost = doc.project?.climate?.frost_mm ?? 750;
  _auto = { skirt: frost, slab: DEFAULTS.slab, beamW: DEFAULTS.beamW, beamD: DEFAULTS.beamD };
  Object.assign(form, _auto);

  document.getElementById('fnd-skirt').value  = round1(form.skirt);
  document.getElementById('fnd-slab').value   = round1(form.slab);
  document.getElementById('fnd-beam-w').value = round1(form.beamW);
  document.getElementById('fnd-beam-d').value = round1(form.beamD);
  document.getElementById('fnd-warn')?.classList.remove('show');

  document.getElementById('foundation-modal').classList.add('open');
  validate();
}

function closeFoundationModal() {
  document.getElementById('foundation-modal').classList.remove('open');
}

function onGo() {
  if (!validate()) return;
  // Replace any prior foundation (defensive — framing-edit invalidation normally
  // clears it first). One foundation entity, params only.
  for (let i = doc.entities.length - 1; i >= 0; i--) {
    if (doc.entities[i].kind === 'foundation') doc.entities.splice(i, 1);
  }
  doc.entities.push({
    id: `foundation_${ui.nextId++}`,
    kind: 'foundation',
    layer: 'foundation',
    level: 'L1',
    params: {
      slab_thickness_mm: form.slab,
      beam_w_mm: form.beamW,
      beam_d_mm: form.beamD,
      skirt_depth_mm: form.skirt,
      skirt_thickness_mm: SKIRT_THICKNESS_MM,
    },
  });
  closeFoundationModal();
  markModelChanged();                                   // rebuild 3D + BOM
  window.dispatchEvent(new Event('iconic:foundation')); // trades.js → review view
}

export function initFoundationModal() {
  const bind = (id, key) => {
    const el = document.getElementById(id);
    el?.addEventListener('input', () => {
      form[key] = parseFloat(el.value);
      validate();
      checkEdited();
    });
  };
  bind('fnd-skirt', 'skirt');
  bind('fnd-slab', 'slab');
  bind('fnd-beam-w', 'beamW');
  bind('fnd-beam-d', 'beamD');
  document.getElementById('fnd-go')?.addEventListener('click', onGo);
}
